# Basic
title: Luis
subtitle: 天作高山，大王荒之。彼作矣，文王康之。
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: A Nest of Luis
creator: <a href="">@FengZhen</a>

url: "https://meybeblank.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: 随笔, description: 偶有所得, url: ''}
    - {title: 摘抄, description: 所喜所见, url: ''}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: FengZhen
    # duoshuo: 
    
# Social
social:
    # weibo: onevcat
    github: meybeBlank
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: 770884946@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
